In [1]:
import numpy as np

In [6]:
arreglo_grados = np.array([0, 30, 45, 60, 90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [7]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [12]:
numero_random = np.random.randint(11)  #numero random entero del 0 al 10  [0, 11[
numero_random

5

In [15]:
numero_random_negativo = np.random.randint(-9, 2)
numero_random_negativo

-3

In [16]:
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([15, 17, 10, 12, 14, 19, 16, 17])

In [17]:
np.average(arreglo_random)

15.0

In [23]:
np.mean(arreglo_random)

15.0

In [19]:
np.median(arreglo_random)

15.5

In [21]:
np.std(arreglo_random)

2.7386127875258306

In [22]:
np.var(arreglo_random)

7.5